version: '2.0'
services: 
    docker_registry:
        image: registry:2
        ports:
        - "5000:5000"
        links:
        - jenkins_master
    jenkins_master:
        image: jenkins/jenkins:lts
        ports:
        - "8080:8080"
        - "50000:50000"
        volumes:
        - jenkins_home:/var/jenkins_home

volumes:
    jenkins_home: {}