#FROM jenkins/jenkins:lts
FROM redpandaci/jenkins-dind:latest

#USER root
#SHELL [ "/bin/bash" ]

RUN apt-get update

# install pkgs
#RUN apt-get install ansible netcat apt-transport-https \
#    curl gnupg2 -y

RUN apt-get install netcat -y

#COPY ./roles /etc/ansible/roles

# install docker-ce via ansible role
#RUN ansible-playbook -i /etc/ansible/roles/dockerd/tests/local_inventory \
#    /etc/ansible/roles/dockerd/tests/playbook.yml \
#    --connection=local

#COPY ./jenkins_home.tar.gz /tmp/
#RUN rm -rf /var/jenkins_home/* && tar -xf /tmp/jenkins_home.tar.gz --strip-components=1 -C /var/jenkins_home
#RUN rm -rf /var/jenkins_home/* && tar -xf /tmp/jenkins_home.tar.gz --strip-components=1 -C /tmp

#RUN java -jar /var/jenkins_home/war/WEB-INF/lib/cli-2.222.1.jar --help
#COPY ./jenkins.sh /usr/local/bin/jenkins.sh

#COPY ./install_podman.sh /tmp/install_podman.sh

#RUN /tmp/install_podman.sh